// <auto-generated />
using System;
using Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251025125639_SeedEvents")]
    partial class SeedEvents
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxParticipants")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2c8e0f9b-18c4-45d7-b48b-09b55f585935"),
                            Category = "Technology",
                            Description = "Comprehensive conference covering the latest advances in artificial intelligence, machine learning algorithms, and their practical applications in various industries.",
                            ImageUrl = "/images/events/5f8839be-ad91-415d-94d3-5dd4bd55c9b8.jpg",
                            Location = "Moscow, Digital October Center",
                            MaxParticipants = 300,
                            StartDateTime = new DateTime(2025, 6, 15, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "AI & Machine Learning Summit 2025"
                        },
                        new
                        {
                            Id = new Guid("2c8e0f9b-18c4-45d7-b48b-09b55f585936"),
                            Category = "Technology",
                            Description = "Hands-on workshop on cloud technologies, microservices architecture, and DevOps practices for modern software development.",
                            ImageUrl = "/images/events/5f8839be-ad91-415d-94d3-5dd4bd55c9b8.jpg",
                            Location = "St. Petersburg, ITMO University",
                            MaxParticipants = 150,
                            StartDateTime = new DateTime(2025, 4, 22, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            Title = "Cloud Computing Workshop"
                        },
                        new
                        {
                            Id = new Guid("2c8e0f9b-18c4-45d7-b48b-09b55f585937"),
                            Category = "Technology",
                            Description = "Expert discussions on cybersecurity threats, data protection strategies, and emerging security technologies for enterprises.",
                            ImageUrl = "/images/events/5f8839be-ad91-415d-94d3-5dd4bd55c9b8.jpg",
                            Location = "Novosibirsk, Technopark Akademgorodok",
                            MaxParticipants = 250,
                            StartDateTime = new DateTime(2025, 8, 10, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Cybersecurity Conference"
                        },
                        new
                        {
                            Id = new Guid("e3b42b54-ec1f-4b62-ae9a-41de3aef5a58"),
                            Category = "Business",
                            Description = "Competition for innovative startups to present their ideas to investors and industry experts. Prizes include funding opportunities and mentorship.",
                            ImageUrl = "/images/events/5f8839be-ad91-415d-94d3-5dd4bd55c9b8.jpg",
                            Location = "Kazan, IT Park",
                            MaxParticipants = 100,
                            StartDateTime = new DateTime(2025, 5, 18, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Startup Pitch Competition"
                        },
                        new
                        {
                            Id = new Guid("e3b42b54-ec1f-4b62-ae9a-41de3aef5a59"),
                            Category = "Marketing",
                            Description = "Intensive course on modern digital marketing strategies, social media advertising, and content creation for business growth.",
                            ImageUrl = "/images/events/5f8839be-ad91-415d-94d3-5dd4bd55c9b8.jpg",
                            Location = "Yekaterinburg, Ural Federal University",
                            MaxParticipants = 80,
                            StartDateTime = new DateTime(2025, 7, 25, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Digital Marketing Masterclass"
                        },
                        new
                        {
                            Id = new Guid("f4c53c65-fd2e-5c73-bf0b-52ef4bf6b6a0"),
                            Category = "Finance",
                            Description = "Exploring the future of blockchain technology, DeFi protocols, and the impact of cryptocurrencies on traditional finance.",
                            ImageUrl = "/images/events/5f8839be-ad91-415d-94d3-5dd4bd55c9b8.jpg",
                            Location = "Nizhny Novgorod, Lobachevsky University",
                            MaxParticipants = 200,
                            StartDateTime = new DateTime(2025, 9, 12, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Blockchain & Cryptocurrency Forum"
                        },
                        new
                        {
                            Id = new Guid("a5d64d76-ae3f-6d84-ca1c-63fa5ca7c7b1"),
                            Category = "Technology",
                            Description = "Comprehensive bootcamp covering iOS and Android development, cross-platform frameworks, and app store optimization.",
                            ImageUrl = "/images/events/5f8839be-ad91-415d-94d3-5dd4bd55c9b8.jpg",
                            Location = "Rostov-on-Don, Southern Federal University",
                            MaxParticipants = 120,
                            StartDateTime = new DateTime(2025, 10, 8, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            Title = "Mobile App Development Bootcamp"
                        },
                        new
                        {
                            Id = new Guid("b6e75e87-af4a-7e95-da2d-74aa6da8d8c2"),
                            Category = "Technology",
                            Description = "Advanced techniques in data analysis, machine learning models, and big data processing for business intelligence.",
                            ImageUrl = "/images/events/5f8839be-ad91-415d-94d3-5dd4bd55c9b8.jpg",
                            Location = "Vladivostok, Far Eastern Federal University",
                            MaxParticipants = 180,
                            StartDateTime = new DateTime(2025, 11, 20, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Data Science & Analytics Summit"
                        },
                        new
                        {
                            Id = new Guid("c7f86f98-aa5a-8f06-ea3e-85aa7ea9e9d3"),
                            Category = "Technology",
                            Description = "Comprehensive conference on game design, programming, graphics, and the latest trends in the gaming industry.",
                            ImageUrl = "/images/events/5f8839be-ad91-415d-94d3-5dd4bd55c9b8.jpg",
                            Location = "Krasnodar, Kuban State University",
                            MaxParticipants = 220,
                            StartDateTime = new DateTime(2025, 12, 5, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Game Development Conference"
                        },
                        new
                        {
                            Id = new Guid("d8a97a09-aa6a-9a17-fa4f-96aa8fa0f0e4"),
                            Category = "Business",
                            Description = "Strategies for building successful online businesses, e-commerce platforms, and digital transformation in retail.",
                            ImageUrl = "/images/events/5f8839be-ad91-415d-94d3-5dd4bd55c9b8.jpg",
                            Location = "Samara, Samara University",
                            MaxParticipants = 160,
                            StartDateTime = new DateTime(2025, 1, 15, 15, 30, 0, 0, DateTimeKind.Unspecified),
                            Title = "E-commerce & Online Business Summit"
                        },
                        new
                        {
                            Id = new Guid("e9a08a10-aa7a-aa28-aa5a-a7aa9aa1a1f5"),
                            Category = "Design",
                            Description = "Hands-on workshop on user interface and user experience design, prototyping tools, and design thinking methodologies.",
                            ImageUrl = "/images/events/5f8839be-ad91-415d-94d3-5dd4bd55c9b8.jpg",
                            Location = "Tomsk, Tomsk State University",
                            MaxParticipants = 90,
                            StartDateTime = new DateTime(2025, 2, 28, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            Title = "UI/UX Design Workshop"
                        },
                        new
                        {
                            Id = new Guid("f0a19a21-aa8a-ba39-aa6a-b8aa0aa2a2a6"),
                            Category = "Technology",
                            Description = "Exploring Internet of Things technologies, smart city solutions, and connected devices for urban development.",
                            ImageUrl = "/images/events/5f8839be-ad91-415d-94d3-5dd4bd55c9b8.jpg",
                            Location = "Krasnoyarsk, Siberian Federal University",
                            MaxParticipants = 140,
                            StartDateTime = new DateTime(2025, 3, 14, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "IoT & Smart Cities Conference"
                        },
                        new
                        {
                            Id = new Guid("a1a20a32-aa9a-ca40-aa7a-c9aa1aa3a3a7"),
                            Category = "Finance",
                            Description = "Latest innovations in financial technology, digital banking, payment systems, and regulatory compliance in fintech.",
                            ImageUrl = "/images/events/5f8839be-ad91-415d-94d3-5dd4bd55c9b8.jpg",
                            Location = "Perm, Perm State University",
                            MaxParticipants = 170,
                            StartDateTime = new DateTime(2025, 4, 30, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "FinTech Innovation Forum"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Participant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Participants");
                });

            modelBuilder.Entity("Domain.Entities.ParticipantEvent", b =>
                {
                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ParticipantId", "EventId");

                    b.HasIndex("EventId");

                    b.ToTable("ParticipantEvents");
                });

            modelBuilder.Entity("Domain.Entities.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Permission");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Read"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Create"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Update"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Delete"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "User"
                        });
                });

            modelBuilder.Entity("Domain.Entities.RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermission");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            PermissionId = 1
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 2
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 3
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 4
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 1
                        });
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Domain.Entities.UserRole", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RoleId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRole");
                });

            modelBuilder.Entity("Domain.Entities.Participant", b =>
                {
                    b.HasOne("Domain.Entities.User", "User")
                        .WithOne("Participant")
                        .HasForeignKey("Domain.Entities.Participant", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.ParticipantEvent", b =>
                {
                    b.HasOne("Domain.Entities.Event", "Event")
                        .WithMany("ParticipantEvents")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Participant", "Participant")
                        .WithMany("ParticipantEvents")
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("Domain.Entities.RolePermission", b =>
                {
                    b.HasOne("Domain.Entities.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.UserRole", b =>
                {
                    b.HasOne("Domain.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Event", b =>
                {
                    b.Navigation("ParticipantEvents");
                });

            modelBuilder.Entity("Domain.Entities.Participant", b =>
                {
                    b.Navigation("ParticipantEvents");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Navigation("Participant");
                });
#pragma warning restore 612, 618
        }
    }
}
